variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  BACKEND_CONTAINER: "backend"

stages:
   - build
   - release
   - deploy
   
build-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/dumplings-frontend:$CI_COMMIT_SHA"
      --build-arg BACKEND_CONTAINER="$BACKEND_CONTAINER"
      --cache=true
  rules:
    - changes:
      - frontend/**/*

release:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/dumplings-frontend:$CI_COMMIT_SHA $VERSION
  rules:
    - changes:
      - frontend/**/*

deploy-frontend-locally:
  stage: deploy
  image: docker:dind
  before_script:
#    - apk add openssh-client bash
    - apk add --no-cache curl gettext
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Frontend image with version $VERSION creation success."

#    #push image into the nexus
#    - docker login -u ${NEXUS_USERNAME} -p ${NEXUS_REPO_PASS} ${NEXUS_ACCESS_URL} || true
#    - docker push ${NEXUS_ACCESS_URL}/${NEXUS_REPOSITORY_NAME_DOCKER_FRONTEND} || true

    - docker context create remote --docker "host=ssh://${DEPLOYMENT_USER}@${DEPLOYMENT_HOST}" || true
    - docker context use remote

    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker network create -d bridge dumplings_network || true
    
    - docker compose up -d frontend
 
    - outfile="${CI_PROJECT_DIR}/dumplings-store-frontend-$VERSION.tar" &&
      docker save -o $outfile ${CI_REGISTRY_IMAGE}/dumplings-frontend:${VERSION} &&
      curl "${NEXUS_ACCESS_URL}/repository/${NEXUS_REPOSITORY_NAME_DOCKER_FRONTEND}/" 
          --user "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" 
          --upload-file "${outfile}" 
          --verbose 
          --fail

  environment:
    name: staging
    url: "${DUMPLINGS_STORE_URL}"
  rules:
    - if: $DEPLOY_VARIABLE != "manual"
      when: on_success
      allow_failure: false
    - if: $DEPLOY_VARIABLE == "manual"
      when: manual
      allow_failure: true

  
show-deploy-frontend-k8s-info-only:
  stage: deploy
  image: docker:dind
  script:
    - >
      echo "Frontend image created.
      ------------------------
      It's ready to be deployed to the Kubernetes cluster with frontend image-version $VERSION.
      Please, copy this ID and paste to the values.yaml of frontend helm chart file."
    
  rules:
    - if: $DEPLOY_VARIABLE == "manual"
      when: on_success
      allow_failure: false
