stages:
  - module-pipelines
 
variables:
  DEPLOY_VARIABLE: "manual"

#------- DEVELOPMENT
frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
    - backend/**/* 

#--------- INFRASTRUCTURE
kubernetes-apply:
  variables:
    DEPLOY_VARIABLE: "manual"

  stage: module-pipelines
  trigger:
    include:
      - "infrastructure/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - infrastructure/kubernetes/**/*

workflow:
  rules:
    - when: always
