---
groups:
  - name: Dumplings store rules (backend)
    rules:
    - alert: InstanceDown
      expr: up{app="backend"} == 0
      for: 1m
      labels:
        severity: critical
        project: "dumplings_store"
        component: "{{ $labels.app }}"
        namespace: "{{ $labels.kubernetes_namespace }}"
      annotations:
        summary: "Instance {{ $labels.instance }} is down"
        description: "Instance {{ $labels.instance }} of app {{ $labels.app }} has been down for more than 1 minutes."
