---
apiVersion: v2
type: application
name: dumplings-store
description: Dumplings Store Helm Chart

version: 0.1.48
appVersion: "latest"

dependencies:
  - name: backend
    version: 0.1.6
  - name: frontend
    version: 0.1.6 
