{
 "title": "DumplingsStore",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Доступность Backend",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app) (up{app=\"backend\"})"
    }
   ]
  },
  {
   "title": "Обработанных заказов на текущий момент ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (response_timing_ms_bucket{handler=\"/auth/whoami/\", le=\"0.0\"})"
    }
   ]
  },
  {
   "title": "Число запросов",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (requests_count{app=\"backend\"})"
    }
   ]
  },
  {
   "title": "Число заказов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum by (instance) (orders_count{app=\"backend\"})"
    }
   ]
  },
  {
   "title": "99 перцентиль времени обработки запросов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "  histogram_quantile(0.99,\r\n    sum by (le) (\r\n      rate(\r\n        response_timing_ms_bucket{handler=\"/auth/whoami/\"}[5m]\r\n      )\r\n    )\r\n  )\r\n  "
    }
   ]
  }
 ]
}