apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: yc-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "info@${FRONTEND_EXTERNAL_FQDN}"
    privateKeySecretRef:
      name: "${TLS_STORE_SECRET_NAME}"
    solvers:
    - http01:
        ingress:
          class: nginx
